### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by DennisFaucher** [yarrick/pingfs#10]
I just compiled and ran on Linux Mint. Some writes to file system return "Permission Denied". Here are some working, and not working, commands:

$ sudo ./pingfs pinghosts.txt /media/dennis (Working)
$ sudo touch /media/dennis/newfile (Working)
$ sudo ls /media/dennis (Working)
newfile
$ sudo echo Hello > /media/dennis/hello.txt (Not Working)
bash: /media/dennis/hello.txt: Permission denied

Thanks in advance.

**Comment by yarrick** [comment]
I think sudo only applies to the "echo Hello" part, not the redirect. 
Try again with as root.
