### ISSUE TITLE
Possible patent violation 

### ISSUE THREAD

**Issue by stokito** [yarrick/pingfs#12]
PingFS uses a technology from one of firts computers https://en.m.wikipedia.org/wiki/Delay_line_memory

Is any license violation here? Can I use PingFS in production without being suited?

**Comment by yarrick** [comment]
Patents don't usually last that long. I would guess you will have more problems from the abuse department of your ISP and whoever's servers you communicate with.

**Comment by jamestiotio** [comment]
@stokito Looking at the current status of [the relevant patent](https://patents.google.com/patent/US2629827), we can confirm that it has expired. Hence, said invention has become part of the public domain.
