### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [yarrick/pingfs#4]
I would like to point out that identifiers like "[`__FS_H__`](https://github.com/yarrick/pingfs/blob/4b064a9961a1caa68148abc68b5f0a0ad26bdc75/fs.h#L16)" and "[`__ICMP_H__`](https://github.com/yarrick/pingfs/blob/d6ffc214f8f35a7f08ccdbad44ca6ab1f33a2707/icmp.h#L16)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by troglobit** [comment]
@elfring I believe `PINGFS_FS_H_` and `PINGFS_ICMP_H_` would be more fit to the ISO C standard, do you agree?

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/troglobit/pingfs/commit/089fd5e1e90cecc0779818efcf7251a555fbdc81 "Use ISO C header file guards").

**Comment by troglobit** [comment]
@elfring Just realized I didn't make a branch for each fix, so all fixes to outstanding issues are in one big pull request, see #9 for details.

Let me know if you want med to split it up in separate pull requests, one per issue.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/yarrick/pingfs/commit/089fd5e1e90cecc0779818efcf7251a555fbdc81 "Use ISO C header file guards").
