### ISSUE TITLE
Tagging/versioning

### ISSUE THREAD

**Issue by maffblaster** [yarrick/pingfs#6]
Would it be possible to tag a version for this project in git? I can submit a PR if you'd like... @yarrick, thoughts?

**Comment by yarrick** [comment]
I am curious to why. Do you intend to package it?

**Comment by maffblaster** [comment]
@yarrick I'd like to have a more stable way to distribute it, yes. I've put it in an "April Fools" overlay for Gentoo. This repository will host 'cool things that no one should ever use." :)

https://github.com/gentoo/april-fools-overlay
