### ISSUE TITLE
"No superuser required" and "use root" contradict each other

### ISSUE THREAD

**Issue by Qix-** [yarrick/pingfs#8]
In the readme, you say "No superuser required" but then instruct users to use `sudo` to run the FUSE entry point.

IIRC you always have to have root powers to mount. Seems like a mistake in the readme.

Hilarious repo by the way, I love it. 💃

**Comment by MatiasConTilde** [comment]
> It is implemented using raw sockets and FUSE, so superuser powers are required.

"so", not "no"

**Comment by Qix-** [comment]
._. derp, thanks
